let a = "" + 1 + 0;
let b = "" - 1 + 0;
let c = true + false;
let d = 6 / "3";
let e = "2" * "3";
let f = 4 + 5 + "px";
let g = "$" + 4 + 5;
let h = "4" - 2;
let i = "4px" - 2;
let j = "  -9  " + 5;
let k = "  -9  " - 5;
let l = null + 1;
let m = undefined + 1;
let n = " \t \n" - 2;
console.log({ a, b, c, d, e, f, g, h, i, j, k, l, m, n });
